# -*- coding: utf-8 -*-

trigrams = {
    "Ch'ien": [1, 1, 1],
    "K'un": [0, 0, 0],
    "K'an": [0, 1, 0],
    "Chên": [1, 0, 0],
    "Kên": [0, 0, 1],
    "Sun": [0, 1, 1],
    "Tui": [1, 1, 0],
    "Li": [1, 0, 1]
}

hexagrams = {
    "Ta Yu": trigrams["Ch'ien"] + trigrams["Li"],
    "Ku": trigrams["Sun"] + trigrams["Kên"],
    "I (Corner of the Mouth": trigrams["Chên"] + trigrams["Tui"],
    "Ta Ch'u": trigrams["Ch'ien"] + trigrams["Kên"],
    "Lü": trigrams["Tui"] + trigrams["Ch'ien"],
    "Sui": trigrams["Chên"] + trigrams["Tui"],
    "Li": trigrams["Li"] + trigrams["Li"],
    "Shih Ho": trigrams["Chên"] + trigrams["Li"],
    "Lin": trigrams["Tui"] + trigrams["K'un"],
    "Ta Kuo": trigrams["Sun"] + trigrams["Tui"],
    "Mêng": trigrams["K'an"] + trigrams["Kên"],
    "Kuan": trigrams["K'un"] + trigrams["Sun"],
    "P'i": trigrams["K'un"] + trigrams["Ch'ien"],
    "Pi": trigrams["Li"] + trigrams["Kên"],
    "Po": trigrams["K'un"] + trigrams["Kên"],
    "K'un": trigrams["K'un"] + trigrams["K'un"],
    "Shih": trigrams["K'an"] + trigrams["K'un"],
    "Fu": trigrams["Chên"] + trigrams["K'un"],
    "Yü": trigrams["K'un"] + trigrams["Chên"],
    "Chun": trigrams["Chên"] + trigrams["K'an"],
    "Wu Wang": trigrams["Chên"] + trigrams["Ch'ien"],
    "Hsiao Ch'u": trigrams["Ch'ien"] + trigrams["Sun"],
    "T'ai": trigrams["Ch'ien"] + trigrams["K'un"],
    "Ch'ien": trigrams["Kên"] + trigrams["K'un"],
    "T'ung Jên": trigrams["Li"] + trigrams["Ch'ien"],
    "Hêng": trigrams["Sun"] + trigrams["Chên"],
    "Hsien": trigrams["Kên"] + trigrams["Tui"],
    "Sung": trigrams["K'an"] + trigrams["Ch'ien"],
    "Hsü": trigrams["Ch'ien"] + trigrams["K'an"],
    "K'an": trigrams["K'an"] + trigrams["K'an"],
    "Tun": trigrams["K'en"] + trigrams["Ch'ien"],
    "Ta Chuang": trigrams["Ch'ien"] + trigrams["Chên"],
    "Chin": [0, 0, 0, 1, 0, 1],
    "Ming I": [1, 0, 1, 0, 0, 0],
    "Chia Jên": [1, 0, 1, 0, 1, 1],
    "K'uei": [1, 1, 0, 1, 0, 1],
    "Chien (Obstruction)": [0, 0, 1, 0, 1, 0],
    "Hsieh": [0, 1, 0, 1, 0, 0],
    "Sun (Decrease)": [1, 1, 0, 0, 0, 1],
    "I (Increase)": [1, 0, 0, 0, 1, 1],
    "Kuai": [1, 1, 1, 1, 1, 0],
    "Kou": [0, 1, 1, 1, 1, 1],
    "Ts'ui": [0, 0, 0, 1, 1, 0],
    "Shêng": [0, 1, 1, 0, 0, 0],
    "K'un": [0, 1, 0, 1, 1, 0],
    "Ching": [0, 1, 1, 0, 1, 0],
    "Ko": [1, 0, 1, 1, 1, 0],
    "Ting": [0, 1, 1, 1, 0, 1],
    "Chên": [1, 0, 0, 1, 0, 0],
    "Kên": [0, 0, 1, 0, 0, 1],
    "Chien (Development)": [0, 0, 1, 0, 1, 1],
    "Kuei Mei": [1, 1, 0, 1, 0, 0],
    "Fêng": [1, 0, 1, 1, 0, 0],
    "Lü": [0, 0, 1, 1, 0, 1],
    "Sun (The Gentle)": [0, 1, 1, 0, 1, 1],
    "Tui": [1, 1, 0, 1, 1, 0],
    "Huan": [0, 1, 0, 0, 1, 1],
    "Chieh": [1, 1, 0, 0, 1, 1],
    "Chung Fu": [1, 1, 0, 0, 1, 1],
    "Hsiao Kuo": [0, 0, 1, 1, 0, 0],
    "Chi Chi": [1, 0, 1, 0, 1, 0],
    "Wei Chi": [0, 1, 0, 1, 0, 1]
}
